# Generated by Django 5.2.11 on 2026-04-16 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lungreport',
            name='patient_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lungreport',
            name='status',
            field=models.CharField(choices=[('Unrequested', 'Awaiting Action'), ('Pending', 'Pending Review'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Unrequested', max_length=20),
        ),
    ]
