# Generated by Django 5.2.11 on 2026-04-16 16:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0002_lungreport_patient_notes_alter_lungreport_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='lungreport',
            name='requested_doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_scans', to=settings.AUTH_USER_MODEL),
        ),
    ]
