# Generated by Django 6.0.2 on 2026-04-26 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0003_lungreport_requested_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='lungreport',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
