# Generated by Django 6.0.2 on 2026-04-28 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0006_prescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='mode',
            field=models.CharField(choices=[('Online', 'Online Video Call'), ('Offline', 'In-Person Visit')], default='Online', max_length=10),
        ),
    ]
