# Generated by Django 6.0.2 on 2026-04-29 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0008_user_allergies_user_current_medications_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='reminder_sent',
            field=models.BooleanField(default=False),
        ),
    ]
