# Generated by Django 6.0.2 on 2026-04-29 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0009_consultation_reminder_sent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='detector.lungreport'),
        ),
    ]
