# Generated by Django 6.0.2 on 2026-04-29 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0010_alter_consultation_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='next_consultation_date',
            field=models.DateField(blank=True, help_text='Date recommended by doctor for next follow-up', null=True),
        ),
    ]
